name: plank
description: >
  A simple and extensible logger
version: 0.0.1
author: Andres Araujo a.araujo.azua@gmail.com
#homepage: https://www.example.com

dependencies:
  logging: any
  ansicolor: ">=0.0.9 <0.1.0"
dev_dependencies:
  unittest: any
