name: plank
description: >
  A simple and extensible logger
version: 0.0.1
author: Andres Araujo a.araujo.azua@gmail.com
#homepage: https://www.example.com

dependencies:
  logging: any
dev_dependencies:
  unittest: any
